<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BrzCepModule\Module'                                 => __DIR__ . '/Module.php',
    'BrzCepModule\Adapter\CepAdapterInterface'            => __DIR__ . '/src/BrzCepModule/Adapter/CepAdapterInterface.php',
    'BrzCepModule\Adapter\CorreioControlAdapter'          => __DIR__ . '/src/BrzCepModule/Adapter/CorreioControlAdapter.php',
    'BrzCepModule\Adapter\PostmonAdapter'                 => __DIR__ . '/src/BrzCepModule/Adapter/PostmonAdapter.php',
    'BrzCepModule\Adapter\RepublicaVirtualAdapter'        => __DIR__ . '/src/BrzCepModule/Adapter/RepublicaVirtualAdapter.php',
    'BrzCepModule\Adapter\ViaCepAdapter'                  => __DIR__ . '/src/BrzCepModule/Adapter/ViaCepAdapter.php',
    'BrzCepModule\Controller\CepController'               => __DIR__ . '/src/BrzCepModule/Controller/CepController.php',
    'BrzCepModule\Exception\CepNotFoundException'         => __DIR__ . '/src/BrzCepModule/Exception/CepNotFoundException.php',
    'BrzCepModule\Exception\EnderecoFormatException'      => __DIR__ . '/src/BrzCepModule/Exception/EnderecoFormatException.php',
    'BrzCepModule\Exception\EnderecoResponseException'    => __DIR__ . '/src/BrzCepModule/Exception/EnderecoResponseException.php',
    'BrzCepModule\Factory\CepControllerFactory'           => __DIR__ . '/src/BrzCepModule/Factory/CepControllerFactory.php',
    'BrzCepModule\Factory\CepServiceFactory'              => __DIR__ . '/src/BrzCepModule/Factory/CepServiceFactory.php',
    'BrzCepModule\Factory\CorreioControlAdapterFactory'   => __DIR__ . '/src/BrzCepModule/Factory/CorreioControlAdapterFactory.php',
    'BrzCepModule\Factory\PostmonAdapterFactory'          => __DIR__ . '/src/BrzCepModule/Factory/PostmonAdapterFactory.php',
    'BrzCepModule\Factory\RepublicaVirtualAdapterFactory' => __DIR__ . '/src/BrzCepModule/Factory/RepublicaVirtualAdapterFactory.php',
    'BrzCepModule\Factory\ViaCepAdapterFactory'           => __DIR__ . '/src/BrzCepModule/Factory/ViaCepAdapterFactory.php',
    'BrzCepModule\Response\EnderecoResponse'              => __DIR__ . '/src/BrzCepModule/Response/EnderecoResponse.php',
    'BrzCepModule\Response\EnderecoResponseInterface'     => __DIR__ . '/src/BrzCepModule/Response/EnderecoResponseInterface.php',
    'BrzCepModule\Service\CepService'                     => __DIR__ . '/src/BrzCepModule/Service/CepService.php',
);
